### ISSUE TITLE
Homematic Manager, Ladevorgang endlos

### ISSUE THREAD

**Issue by github6043** [hobbyquaker/homematic-manager#121]
Hi all

Habe mir eben den Homematic Manager 2.5.0 installiert. Die Verbindung zur Debmatic steht.
Jedoch werden keine devices importiert, Manager steht bei Ladevorgang ... und list ist leer.

Kennt jemand Abhilfe ?

**Comment by github6043** [comment]
Kriege da mit der Version 2.6.2 Javascript Errors

Unhandled Error
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ipcRpc.send (C:/Users/juerg/AppData/Local/Programs/homematic-manager/resources/app.asar/www/js/homematic-manager.js:411:20)
    at EventEmitter.Rpc.ipc.on (C:/Users/juerg/AppData/Local/Programs/homematic-manager/resources/app.asar/node_modules/electron-ipc-rpc/index.js:26:17)

**Comment by github6043** [comment]
![2019-11-20 13_31_59-Window](https://user-images.githubusercontent.com/40850921/69239680-13e78d80-0b9b-11ea-8f67-2f4fab6aceb7.png)
![2019-11-20 13_36_21-Window](https://user-images.githubusercontent.com/40850921/69239687-16e27e00-0b9b-11ea-8164-afa69d1a50c2.png)

**Comment by harabeck** [comment]
Auch bei mir ist der Ladevorgang endlos, obwohl eine Verbindung zu BidCos mit grünem Hakeb erfolgreich ist. Habe Windos 10 Defender Firewall deaktiviert, auch der App entsprechende Rechte vergeben. Keine Änderung. Zu Java Script Errors kann ich nichts sagen, sehe keine, wo wäre das Logfile zu finden?

Ab Homemativ Manager Version 2.3.0 kommt der Ladevorgang nicht zum Ende. Deinstallieren und Version 2.2.0 funktioniert sofort einwandfrei.

Woran kan das liegen?

**Comment by dasFelix** [comment]
Hallo
Hatte ich auch mit win10. Ebenfalls dass 2.2.0 gleich lief, nachdem ich es hier gesehen habe. Hatte allerdings ein JavaUpdate pending und dies installiert. Nun läuft auch die V2.6.2 ohne Probleme.

**Comment by dasFelix** [comment]
Sorry... kommando zurück. Beim nächsten Start war das Problem leider wieder da :(

**Comment by harabeck** [comment]
Auch bei mir war der Ladevorgang endlos. Die Lösung war die alte Version zunächst deinstallieren und anschliessend die aktuelle installieren. Ich hatte bisher einfach die neue Version drüber installiert, das hat das Problem verursacht.

**Comment by Sickboy78** [comment]
Auch bei mir war der Ladevorgang endlos (mit 2.5.0 und 2.6.2). Bisher leider keine der genannten Lösungen geholfen, weder Java Update, noch FW deaktivieren, noch deinstallieren/neuinstallieren.
Einzige Abhilfe, weiterhin alte Version 2.2.0 verwenden.

**Comment by m-hund** [comment]
Bei mir leider auch: Unendlicher Ladevorgang - nichts kommt. Die Verbindung zur CCU scheint aber zu funktionieren; im Fenster wird oben angezeigt, dass BidCos, HmIP verbunden sind. Änderungen an Firewall, Neuinstallation verschiedener Versionen hat nichts gebracht. Gibt es hierzu einen Tipp?

**Comment by widmann-it** [comment]
Leider bei mir auch unter der 2.7.0, gibt es ein logfile wo ich sehen kann was passiert ?

**Comment by real-fakeuser** [comment]
Hello there,
i got the same issue where Homematic Manager starts up and tries to load data into gui. In the Geräte tab the blue Ladevorgang... box disappears when clicking on the reload button but still doesn't show any devices. However it shows a successfull connection with a green arrow at the right side of BidCos-RF
I already tried reinstalling, updating Java 64 bit, run as administrator, disable firewall, disable virus real time scanner. When trying version 2.2.1 i also got java errors msgbox. 
Between tests i deleted Files in Roaming and local/Programs o.ä.
In my case i first installed manager version 1.5 before i saw that there is a newer version available which kind of worked.
My System running is homegear paspberry image on a raspberry pi3+ and iobroker in VM on different system which i also disconnected for testing. My client is running windows 10 pro 64 Bit.
I've read something about editing a config file for propper functioning.
Thanks for this awesome software. I hope there's an easy fix.
Best regards

**Comment by KenkiCK** [comment]
Hi all,
I have after install 2.7 the same issue - looks like virtual devices  makes a problem. Sometimes it never end, sometimes I get the Java error like described. I hope too that this will be fixed.
Bests, Christian

**Comment by f00f** [comment]
Same here. I tried 2.7.0 standalone, 2.6.1 standalone and 2.7.0 setup. Win 10, Firewall turned off. CCU3.

Loading never finishes, list is empty. Green check-marks at the top do appear (BidCos-RF, HmIP, Virtual Devices).

I tried all kinds of settings (Auth on/off, TLS on/off, unhandled exceptions on/off)

Any way of debugging this issue?

**Comment by mnemo70** [comment]
I figured out what is happening: The UI is requesting the application's internal configuration data from the main process so quickly that it hasn't finished initializing it yet.

In the source code file www/js/homematic-manager.js, at line 174, change `getConfig();` to:
```
setTimeout(() => {
    getConfig();
}, 1000);
```

This will delay the getConfig call by a second, giving the main process time to initialize. If the application still hangs, try increasing the value from 1000 to 1500, 2000 or even higher.

Sadly, I cannot provide a new binary to y'all.

**Comment by mnemo70** [comment]
Workaround (for Windows):

1. Download and INSTALL "homematic-manager-setup-2.7.0.exe".
2. Download and install Node.JS if you haven't.
3. Install asar: `npm install -g asar`
4. Open a command prompt, then:
```
cd %localappdata%
cd programs\homematic-manager\resources
asar e app.asar app
ren app.asar app.asar.bak
```
(Adapt the path in the CD commands if you installed Homematic Manager to a different directory.)
5. Open the file app\www\js\homematic-manager.js in an editor.
6. Search for "getConfig"
7. Replace the line "`getConfig();`" with:
```
setTimeout(() => {
    getConfig();
}, 1000);
```
8. Save the file and exit the editor.
9. Run Homematic Manager. The application should work now.

10. If you want, you can re-package the app in the resources directory with:
`asar p app app.asar`
11. Delete the directory "app".

This hack can surely be adopted to the Mac and Linux releases. You just need to find the app.asar file after installation.

**Comment by mnemo70** [comment]
Sorry, another update.

This fix didn't work for a friend who had the "Ladevorgang" problem in macOS.

The difference is that in his Homematic Manager the various device types like Bidcos-RF, HMIP, etc. are NOT displayed below the IP of his CCU. On my machine, the device types are displayed. So he's having another problem...

**Comment by Seestern93** [comment]
> 
> 
> Workaround (for Windows):
> 
>     1. Download and INSTALL "homematic-manager-setup-2.7.0.exe".
> 
>     2. Download and install Node.JS if you haven't.
> 
>     3. Install asar: `npm install -g asar`
> 
>     4. Open a command prompt, then:
> 
> 
> ```
> cd %localappdata%
> cd programs\homematic-manager\resources
> asar e app.asar app
> ren app.asar app.asar.bak
> ```
> 
> (Adapt the path in the CD commands if you installed Homematic Manager to a different directory.)
> 5. Open the file app\www\js\homematic-manager.js in an editor.
> 6. Search for "getConfig"
> 7. Replace the line "`getConfig();`" with:
> 
> ```
> setTimeout(() => {
>     getConfig();
> }, 1000);
> ```
> 
>     1. Save the file and exit the editor.
> 
>     2. Run Homematic Manager. The application should work now.
> 
>     3. If you want, you can re-package the app in the resources directory with:
>        `asar p app app.asar`
> 
>     4. Delete the directory "app".
> 
> 
> This hack can surely be adopted to the Mac and Linux releases. You just need to find the app.asar file after installation.

Thank you for that detailed step-by-step explanation! Worked for me on Windows 10 machine after having problems to connect Homematic-Manager with my RaspberryPi where homegear is running with a nanoCUL stick.
Already connected devices are now shown up as expected, and pairing new devices is now also working :-)

**Comment by f00f** [comment]
Thanks for the detailed instructions, @mnemo70. However, they don't work for me on Win10. I added an `alert()` to verify that the updated `.js` file was being used.

**Comment by jonaswre** [comment]
I still have the same error. Even with the steps shown above. Any further ideas?

**Comment by jonaswre** [comment]
I had the same error. The issue is that there might not be enough time to "findInterfaces()" this results in config.daemons to be undefined.  

There is one simple workaround: 

> Workaround (for Windows):
> 
> 1. Download and INSTALL "homematic-manager-setup-2.7.0.exe".
> 2. Download and install Node.JS if you haven't.
> 3. Install asar: `npm install -g asar`
> 4. Open a command prompt, then:
> 
> ```
> cd %localappdata%
> cd programs\homematic-manager\resources
> asar e app.asar app
> ren app.asar app.asar.bak
> ```
> 
> (Adapt the path in the CD commands if you installed Homematic Manager to a different directory.)
> 5. Open the file app\www\js\homematic-manager.js in an editor.
> 6. Search for "getConfig"
> 7. Replace the line "`getConfig();`" with:
> 
> ```
> setTimeout(() => {
>     getConfig();
> }, 1000);
> ```
> 
> 1. Save the file and exit the editor.
> 2. Run Homematic Manager. The application should work now.
> 3. If you want, you can re-package the app in the resources directory with:
>    `asar p app app.asar`
> 4. Delete the directory "app".
> 
> This hack can surely be adopted to the Mac and Linux releases. You just need to find the app.asar file after installation.

But increase setTimeout to something over 5000 since findInterfaces() times out after 5000ms I choose 6000. This means there is 6000ms delay when starting but this is ok for me. 

Another option would be to only responde with the correct config once its correctly loaded.

**Comment by f00f** [comment]
If I set the timeout to 5000 I get the empty user interface.
If I set the timeout to 6000 homematic manager is stuck at the "Loading Homematic Manager" screen.
So, this didn't work for me either :-(

**Comment by jonaswre** [comment]
Have you tried to increase it further? I've testet with 10000ms

**Comment by ad1240de** [comment]
I have the same problem CCU3 / Win10 blue 'Loading' on the screen and not more..  I try with big timeout , same effort.
With 'show unhandled error' in Config i get Info:
 Unhandled Error
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ipcRpc.send (C:/Users/Andy/AppData/Local/Programs/homematic-manager/resources/app/www/js/homematic-manager.js:454:20)
    at EventEmitter.Rpc.ipc.on (C:/Users/Andy/AppData/Local/Programs/homematic-manager/resources/app/node_modules/electron-ipc-rpc/index.js:26:17)

Andreas

**Comment by mschlenstedt** [comment]
Same Problem with my installation. https://github.com/hobbyquaker/homematic-manager/issues/121#issuecomment-749725958 helps. Now Homematic Manager starts fine.

**Comment by 36grad** [comment]
Same issue on my Win10 machine, also here https://github.com/hobbyquaker/homematic-manager/issues/121#issuecomment-749725958 helped, but I had to set the timeout to 20000 (i.e. 20s) - I wonder what's wrong on my machine.

But then I'm glad that I could get this rather nice tool to work with the described hack.

**Comment by corgan2222** [comment]
> Workaround (for Windows):
> 
>     1. Download and INSTALL "homematic-manager-setup-2.7.0.exe".
> 
>     2. Download and install Node.JS if you haven't.
> 
>     3. Install asar: `npm install -g asar`
> 
>     4. Open a command prompt, then:
> 
> 
> ```
> cd %localappdata%
> cd programs\homematic-manager\resources
> asar e app.asar app
> ren app.asar app.asar.bak
> ```
> 
> (Adapt the path in the CD commands if you installed Homematic Manager to a different directory.) 5. Open the file app\www\js\homematic-manager.js in an editor. 6. Search for "getConfig" 7. Replace the line "`getConfig();`" with:
> 
> ```
> setTimeout(() => {
>     getConfig();
> }, 1000);
> ```
> 
>     8. Save the file and exit the editor.
> 
>     9. Run Homematic Manager. The application should work now.
> 
>     10. If you want, you can re-package the app in the resources directory with:
>         `asar p app app.asar`
> 
>     11. Delete the directory "app".
> 
> 
> This hack can surely be adopted to the Mac and Linux releases. You just need to find the app.asar file after installation.

still works fine! Thanks!

**Comment by MichaelKetting** [comment]
Same issue. Tried the workaround and didn't resolve my problem. Did someone already identify where the problem is originating? Is it a configuration mistake that must be fixed manually or something else. I didn't go into the source code yet to find out what exactly is going on during the load.

**Comment by mnemo70** [comment]
> Same issue. Tried the workaround and didn't resolve my problem. Did someone already identify where the problem is originating? Is it a configuration mistake that must be fixed manually or something else. I didn't go into the source code yet to find out what exactly is going on during the load.

Did you try increasing the timeout to 10000 ms in the workaround?
Is the correct CCU IP address displayed in the top bar on the right (right next to "Ereignisse" or "Events")?
Are there daemon names displayed below that, like "BidCos-RF", "HmIP" or "VirtualDevices"?

**Comment by MichaelKetting** [comment]
@mnemo70 
Yeah, tried 20.000 ms.
Tried the IP address and the hostname that's resolvable via the browser. 
No daemon names are displayed below the IP-address/hostname

**Comment by mnemo70** [comment]
> @mnemo70 Yeah, tried 20.000 ms. Tried the IP address and the hostname that's resolvable via the browser. No daemon names are displayed below the IP-address/hostname

OK...
Are you running the app on Windows, Mac or Linux?
Is "Auth" configured for the connection and are the user and password *really* correct?
Which files are in %appdata%\hm-manager (if you're on Windows)?

**Comment by MichaelKetting** [comment]
@mnemo70 I figured out what the problem was:

My ccu3 still had the firewall turned up to 11, which was intentional but is kind of embarressing, considering...

**Comment by mnemo70** [comment]
> @mnemo70 I figured out what the problem was:
> 
> My ccu3 still had the firewall turned up to 11, which was intentional but is kind of embarressing, considering...

I was suspecting something like that. :) Good that it's working now!

**Comment by hardliner76** [comment]
Mit Windows 11 nicht ans laufen bekommen. Die Executable auf Windows 8 Kombatibilitätsmodus setzen und die Firewall ist für Privat und Öffentlich aktiv. Es funktioniert ohne etwaiges modifizieren von Dateien

**Comment by hobbyquaker** [comment]
Behoben in 3.0.0-beta.0.

Die Ursache ist die, die @mnemo70 und @jonaswre hier richtig beschrieben haben: die Oberfläche holt die Konfiguration ab, bevor die Schnittstellen-Erkennung fertig ist, `config.daemons` ist `undefined`, und danach passiert nichts mehr. Dieses Rennen gibt es in 3.0 nicht mehr — der Schnittstellen-Manager hat einen richtigen init/Ping-Watchdog/Re-init-Ablauf, die Port-Erkennung läuft im Hintergrund und blockiert die Oberfläche nie, und eine Schnittstelle, deren Port zumacht, wird als nicht vorhanden markiert, statt den Start aufzuhalten [#121, #126, #134, #93]. Der `setTimeout`-Hack wird nicht mehr gebraucht.

Für den zweiten Fall aus dem Thread — die CCU-Adresse steht oben, aber keine Schnittstellen darunter — war die Ursache meist die CCU-Firewall. Auch das sieht man in 3.0 sofort, weil nicht erreichbare Schnittstellen im Kopf markiert werden, statt still zu fehlen.

Danke an alle, die hier über fünf Jahre mitgesucht und den Workaround gepflegt haben.

_In short: fixed in 3.0.0-beta.0 — the `getConfig` race is gone, no `setTimeout` patch needed. Downloads: https://github.com/hobbyquaker/homematic-manager/releases/tag/v3.0.0-beta.0_

---
_Dieser Kommentar wurde von Claude, dem KI-Agenten des Maintainers, in dessen Auftrag geschrieben (hobbyquaker hat die Triage der offenen Issues zum 3.0-Beta-Release beauftragt). / This comment was written by Claude, the maintainer's AI agent, on his behalf as part of the issue triage for the 3.0 beta._
