### ISSUE TITLE
Fehler beim Aufruf: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by MarkSau** [hobbyquaker/homematic-manager#126]
```
Unhandled Error
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ipcRpc.send (C:/Users/sauer/AppData/Local/Programs/homematic-manager/resources/app.asar/www/js/homematic-manager.js:452:20)
    at EventEmitter.Rpc.ipc.on (C:/Users/sauer/AppData/Local/Programs/homematic-manager/resources/app.asar/node_modules/electron-ipc-rpc/index.js:26:17)

Homematic Manager Version 2.7.0
Windows 10 2004
```

**Comment by Mihaeru** [comment]
Gleiches Problem bei mir mit der gleichen Version. Ist allerdings auch das erste Mal, dass ich den Homematic Manager benutze. Ältere Versionen habe ich (noch) nicht getestet,
Mein BS: Windows 10 Professional 64bit V2004.

**Comment by hlugt** [comment]
Hallo, habe auch ältere versionen bis 2.6.1 probiert: alle gleiche problem an Windows 10, 64bit v2004.

**Comment by eertraw** [comment]
Hi there, I had the same exception. In my case the INBOX of the Raspmatic had a pending adoption of a HmIP-BWTH device. After adding this device to my Raspmatic, the exception on startup of Homematic Manager disappeared. Maybe you have the same cause.  

_Windows 10.0.19041
Homematic Manager 2.7.0
Raspmatic 3.53.30.20200919_

**Comment by mnemo70** [comment]
See issue #121 for a fix and workaround.

**Comment by hobbyquaker** [comment]
Das ist derselbe Fehler wie #121: die Oberfläche holt die Konfiguration ab, bevor die Schnittstellen-Erkennung durch ist, `config.daemons` ist dann `undefined`. Mit 3.0.0-beta.0 ist er erledigt — der Startablauf ist neu gebaut, mit init, Ping-Watchdog und Re-init, und die Port-Erkennung läuft im Hintergrund statt in einem Rennen gegen einen 5-Sekunden-Timeout [#121, #126, #134, #93]. Der `setTimeout`-Workaround aus dem Thread wird nicht mehr gebraucht.

Beta: https://github.com/hobbyquaker/homematic-manager/releases/tag/v3.0.0-beta.0

---
_Dieser Kommentar wurde von Claude, dem KI-Agenten des Maintainers, in dessen Auftrag geschrieben (hobbyquaker hat die Triage der offenen Issues zum 3.0-Beta-Release beauftragt). / This comment was written by Claude, the maintainer's AI agent, on his behalf as part of the issue triage for the 3.0 beta._
