### ISSUE TITLE
JavaScript Errors beim Start unter macOS 11.0.1

### ISSUE THREAD

**Issue by djiwondee** [hobbyquaker/homematic-manager#127]
Hallo,

vielleicht bin ich der erste, der den Homematic Manager unter Big Sur ausprobiert. Leider kommen nur Fehlermeldungen nach dem Start. Auch nach dem Konfigurieren der IP-Adressen der CCU und das Rechners, auf dem der Homematic Manager läuft.

Gebe hier mal einen kurzen Ablauf der Meldungen

<img width="299" alt="image" src="https://user-images.githubusercontent.com/37173958/101495407-d520a300-3968-11eb-8250-e4fb5f022692.png">

```
Uncaught Exception:
Error: 401 Unauthorized
at Request.request [as _callback] (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/homematic-rega/index.js:108:30)
at Request.self.callback (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
at Request.emit (events.js:182:13)
at Request.<anonymous> (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
at Request.emit (events.js:182:13)
at IncomingMessage.<anonymous> (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:273:13)
at IncomingMessage.emit (events.js:187:15)
at endReadableNT (_stream_readable.js:1092:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

<img width="404" alt="image" src="https://user-images.githubusercontent.com/37173958/101495453-dfdb3800-3968-11eb-9fc4-b0e658d9014d.png">

Umschalten auf Homematic IP in der Combo-Box:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/37173958/101495537-f41f3500-3968-11eb-8216-3d3edd09443f.png">

<img width="301" alt="image" src="https://user-images.githubusercontent.com/37173958/101495587-00a38d80-3969-11eb-8379-b3e22544aa9d.png">

<img width="294" alt="image" src="https://user-images.githubusercontent.com/37173958/101495608-06996e80-3969-11eb-8dc7-6280dd673c66.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/37173958/101495733-292b8780-3969-11eb-9d1a-fb66e20c9ab3.png">

Die ein oder andere Meldungen erscheint nach einem erneuten Restart nicht, wenn man die macOS Firewall deaktiviert resp. dem Homematic Manager erlaubt, eingehende Verbindungen zu akzeptieren:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/37173958/101495957-70b21380-3969-11eb-8654-6a4dcb59b97d.png">

**Comment by hobbyquaker** [comment]
Behoben in 3.0.0-beta.0. ReGa ist jetzt **optional**: sie liefert die Klarnamen, mehr nicht, und ein Fehler von dort ist nie fatal — eine 401 zeigt einen Statushinweis, die App arbeitet mit den lokal gespeicherten Namen weiter und stürzt nicht mehr ab [#127]. Systeme ganz ohne ReGa (Homegear, blankes rfd/hmipserver) funktionieren vollständig.

Auch der Startablauf ist neu: init, Ping-Watchdog und Re-init, und die Port-Erkennung blockiert die Oberfläche nicht mehr [#121]. Unbehandelte Fehler werden immer protokolliert, und der Dialog erscheint einmal statt einmal pro Fehler.

Zum Testen (macOS 12+, universal dmg): https://github.com/hobbyquaker/homematic-manager/releases/tag/v3.0.0-beta.0

---
_Dieser Kommentar wurde von Claude, dem KI-Agenten des Maintainers, in dessen Auftrag geschrieben (hobbyquaker hat die Triage der offenen Issues zum 3.0-Beta-Release beauftragt). / This comment was written by Claude, the maintainer's AI agent, on his behalf as part of the issue triage for the 3.0 beta._
