### ISSUE TITLE
Every few seconds error message "Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by h0ly0ne** [hobbyquaker/homematic-manager#55]
This error happens in an interval of around 5 seconds. It seems the main operation
of the application is working as intended.

Tested with homegear version 0.7.9-1357 and 0.8.0-1837 - error remains.
Used most recent binary build (2.0.0.beta0)

Additional information from homegear.log:
RPC client: Info: Reading from RPC server timed out. Server: x.x.x.x

**Comment by traxanos** [comment]
Same problem here...

**Comment by irqnet** [comment]
same here

**Comment by jurgenhaas** [comment]
Same here on Ubuntu 16.04

**Comment by jampy** [comment]
me tooo...

Manager client on Win10 with Homegear on Debian Jessie. 

RPC commands incompatibility?

**Comment by Venice-89** [comment]
same problem on windows 10 :/

**Comment by hobbyquaker** [comment]
You're all using homegear? I must admit that I never tested it with Homegear... Can't promise when I will find time to look into this... Only thing I could suggest now is to use the "old" non-electron Version of hm-manager: https://github.com/hobbyquaker/homematic-manager/tree/847c2ce15e3ad9de9702242cfd95b2386576b4fa

**Comment by JanLochi** [comment]
Same problem on Ubuntu 16.04, and yes... Using homegear

**Comment by dermeb** [comment]
Just for the record: same thing here.
Linux Mint 18, kernel 4.13 and homegear

**Comment by tomquist** [comment]
Here's a full stacktrace:
```
Uncaught Exception:
TypeError: Cannot read property 'toString' of null
    at Object.decodeData (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/binrpc/lib/protocol.js:414:81)
    at rec (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/binrpc/lib/protocol.js:477:32)
    at Object.decodeStrangeRequest (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/binrpc/lib/protocol.js:486:9)
    at Object.decodeRequest (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/binrpc/lib/protocol.js:522:28)
    at Socket.<anonymous> (/Applications/Homematic Manager.app/Contents/Resources/app.asar/node_modules/binrpc/lib/server.js:53:38)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

**Comment by Mik-** [comment]
I created a [pull request ](https://github.com/hobbyquaker/binrpc/pull/2) on the binrpc module, which solves this issue for me.

**Comment by solars** [comment]
is this included in the .deb? I still have this error

**Comment by hobbyquaker** [comment]
Sorry, forgot to release the build *facepalm
In https://github.com/hobbyquaker/homematic-manager/releases/tag/2.0.0-beta.2 the fix is included
